# Generated by Django 4.1.4 on 2023-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title2',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
